on:
  workflow_dispatch:

jobs:
  pyinstaller-build:
    runs-on: [windows-latest, macos-latest, macos-13]
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.9'
          requirements: 'src/requirements.txt'
          upload_exe_with_name: 'Executable'
          spec: 'src/main.py'
          options: -F, --noconsole, --name "COSLAB", --add-data="src/ui:ui" 
