on:
  workflow_dispatch:

jobs:
  pyinstaller-build-macos-arm64:
    runs-on: macos-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.12'
          requirements: 'src/requirements.txt'
          upload_exe_with_name: 'Executable-MacOS-arm64'
          spec: 'src/main.py'
          options: -F, --noconsole, --name "COSLAB", --add-data "src/ui:ui"
  pyinstaller-build-windows:
      runs-on: windows-latest
      steps:
        - name: Create Executable
          uses: sayyid5416/pyinstaller@v1
          with:
            python_ver: '3.12'
            requirements: 'src/requirements.txt'
            upload_exe_with_name: 'Executable-Windows'
            spec: 'src/main.py'
            options: -F, --noconsole, --name "COSLAB", --add-data "src/ui;ui" 
