on:
  workflow_dispatch:

jobs:
  release:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Release"
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          automatic_release_tag: "latest"
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
  pyinstaller-build-macos-arm64:
    runs-on: macos-latest
    steps:
      - name: Create Executable for Mac
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.12'
          requirements: 'src/requirements.txt'
          upload_exe_with_name: 'Executable-MacOS-arm64'
          spec: 'src/main.py'
          options: -F, --noconsole, --name "COSLAB", --add-data "src/ui:ui", --icon src/ui/graphics/coslabicon.png
      - name: Upload 
        uses: actions/upload-artifact@v4
        with:
          name: 'COSLAB-MacOS-arm64'
          path: dist/*.app
          upload_url: ${{ steps.release.outputs.upload_url }}
  pyinstaller-build-macos-intel:
    runs-on: macos-13
    steps:
      - name: Create Executable for Mac
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.12'
          requirements: 'src/requirements.txt'
          upload_exe_with_name: 'Executable-MacOS-intel'
          spec: 'src/main.py'
          options: -F, --noconsole, --name "COSLAB", --add-data "src/ui:ui", --icon src/ui/graphics/coslabicon.png
      - name: Upload 
        uses: actions/upload-artifact@v4
        with:
          name: 'COSLAB-MacOS-intel'
          path: dist/*.app
          upload_url: ${{ steps.release.outputs.upload_url }}
  pyinstaller-build-windows:
      runs-on: windows-latest
      steps:
        - name: Create Executable for Windows
          uses: sayyid5416/pyinstaller@v1
          with:
            python_ver: '3.12'
            requirements: 'src/requirements.txt'
            upload_exe_with_name: 'Executable-Windows'
            spec: 'src/main.py'
            options: -F, --name "COSLAB", --add-data "src/ui;ui", --icon src/ui/graphics/coslabicon.png
        - name: Upload 
          uses: actions/upload-artifact@v4
          with:
            name: 'COSLAB-Windows'
            path: dist/*.exe
            upload_url: ${{ steps.release.outputs.upload_url }}
